# administer this service by browsing to localhost:631
- name: Get the CUPS package installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - cups
  when: cups_install
  tags:
    - download

- name: Put our own /etc/cups/cupsd.conf in place, to permit local LAN admin
  template:
    src: cupsd.conf
    dest: /etc/cups/cupsd.conf

- name: Put an apache2 config file in place
  template:
    src: cups.conf
    dest: "/etc/{{ apache_config_dir }}/"

- name: Create the link for sites-enabled (debuntu)
  file:
    src: /etc/apache2/sites-available/cups.conf
    dest: /etc/apache2/sites-enabled/cups.conf
    state: link
  when: cups_enabled and is_debuntu

- name: Enable services for CUPS (OS's other than Fedora 18)
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - cups
    - cups-browsed
  when: cups_enabled and not is_F18

- name: Enable services for CUPS (Fedora 18, for XO laptops)
  systemd:
    name: cups
    enabled: yes
  when: cups_enabled and is_F18

- name: Start CUPS (Fedora 18, for XO laptops)
  systemd:
    name: cups
    state: started
  when: cups_enabled and is_F18 and not installing

- name: Permit headless admin of CUPS -- only works when CUPS daemon is running
  shell: "cupsctl --remote-admin"
  when: cups_enabled and not installing

- name: Disable services for CUPS (OS's other than Fedora 18)
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - cups
    - cups-browsed
  when: not cups_enabled and not is_F18

- name: Disable services for CUPS (Fedora 18, for XO laptops)
  service:
    name: cups
    state: stopped
    enabled: no
  when: not cups_enabled and is_F18

- name: Add 'cups' to list of services at /etc/iiab/iiab.ini
  ini_file:
    dest: "{{ service_filelist }}"
    section: cups
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: name
      value: CUPS
    - option: description
      value: '"CUPS (Common UNIX Printing System) is a modular printing system that allows a computer to act as a print server. A computer running CUPS is a host that can accept print jobs from client computers, process them, and send them to the appropriate printer."'
    - option: installed
      value: "{{ cups_install }}"
    - option: enabled
      value: "{{ cups_enabled }}"
