# This is for an OS other than Fedora 18

- name: Create kalite_root directory
  file:
    path: "{{ kalite_root }}/httpsrv/static"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Run the setup using 'kalite manage'
  command: "{{ kalite_program }} manage setup --username={{ kalite_admin_user }} --password={{ kalite_admin_password }} --noinput"
  environment:
    KALITE_HOME: "{{ kalite_root }}"
  async: 1800
  poll: 10

- name: Add 'kalite_installed' variable values to {{ iiab_installed }}
  ini_file:
    path: "{{ iiab_installed }}"
    value: kalite_installed
