#!/bin/bash

INVENTORY=ansible_hosts
PLAYBOOK=check-vars.yml
IIAB_STATE_FILE=/etc/iiab/iiab_state.yml
CWD=`pwd`
if [ ! -f $PLAYBOOK ]; then
    echo "Exiting: IIAB Playbook not found."
    echo "Please run this in /opt/iiab/iiab (top level of the git repo)."
    exit 1
fi
# /etc/iiab/iiab_state.yml is mandatory
# must be present when pre-checking local_vars.yml
if [ ! -f  $IIAB_STATE_FILE ]; then
    cat > $IIAB_STATE_FILE << EOF
# DO *NOT* MANUALLY EDIT THIS, THANKS!
# IIAB does NOT currently support uninstalling apps/services.

EOF
fi
Start=`date`
ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local
End=`date`
echo "check-vars run end:   $End"
echo "check-vars run start: $Start"
