# Server Options

- name: ...IS BEGINNING ==================================
  command: echo

- name: SSHD
  include_role:
    name: sshd
  # has no "when: XXXXX_install" flag
  tags: base, sshd

- name: OPENVPN
  include_role:
    name: openvpn
  when: openvpn_install
  tags: openvpn

- name: Configuring wondershaper
  include_tasks: roles/network/tasks/wondershaper.yml
  when: wondershaper_install
  tags: wondershaper, network

- name: Configuring named
  include_tasks: roles/network/tasks/named.yml
  when: FQDN_changed
  tags: named, network, domain

- name: Configuring dhcpd
  include_tasks: roles/network/tasks/dhcpd.yml
  when: FQDN_changed
  tags: dhcpd, network, domain

- name: Configuring Squid
  include_tasks: roles/network/tasks/squid.yml
  when: squid_install
  tags: squid, network, domain

- name: NETWORK
  include_role:
    name: network
  # has no "when: XXXXX_install" flag
  tags: base, network

- name: HOMEPAGE
  include_role:
    name: homepage
  # has no "when: XXXXX_install" flag
  tags: base, homepage

- name: POSTGRESQL
  include_role:
    name: postgresql
  when: postgresql_install
  tags: postgresql, pathagar, moodle

- name: AUTHSERVER
  include_role:
    name: authserver
  when: authserver_install
  tags: olpc, authserver

- name: CUPS
  include_role:
    name: cups
  when: cups_install
  tags: cups

- name: SAMBA
  include_role:
    name: samba
  when: samba_install
  tags: samba

- name: USB-LIB
  include_role:
    name: usb-lib
  when: usb_lib_install
  tags: usb-lib

- name: Create a Python interface to iiab.env
  template: src=roles/1-prep/templates/iiab_env.py.j2
            dest=/etc/iiab/iiab_env.py

- name: Generate the offline documents
  command: /usr/bin/iiab-refresh-wiki-docs
  when: not nodocs

- name: Recording STAGE 4 HAS COMPLETED ==================
  lineinfile: dest=/etc/iiab/iiab.env
              regexp='^STAGE=*'
              line='STAGE=4'
              state=present
