- name: Server Options Installed
  command: echo Server Options Installed

# this script can be sourced to get iiab location
- name: Create iiab.env file
  template: src=roles/1-prep/templates/iiab.env.j2
            dest=/etc/iiab/iiab.env
            owner=root
            group=root
            mode=0644

- name: put a python interface to iiab.env
  template: src=roles/1-prep/templates/iiab_env.py.j2
            dest=/etc/iiab/iiab_env.py

- name: generate the offline documents
  command: /usr/bin/iiab-refresh-wiki-docs
  when: not nodocs

