- name: Start by installing OS's Calibre package
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - calibre
    - calibre-bin
  when: internet_available

# April 5 2018 raspbian is now tracking the latest Calibre with a small delay.
# Should you really want the latest just run the below script standalone, it is
# strongly suggested that waiting for the lastest deb from Raspbian is the best.

- name: Upgrade to testing Calibre - RPi
  command: scripts/calibre-install-latest-rpi.sh
  when: is_rpi and internet_available

- name: Upgrade to tesing Calibre - non-RPi
  command: scripts/calibre-install-latest.sh
  when: not is_rpi and not is_ubuntu_18 and internet_available

- name: Upgrade to unstable Calibre -  all
  command: scripts/calibre-install-unstable.sh
  when: calibre_unstable and internet_available
