- include_vars: roles/mysql/defaults/main.yml
- include_vars: roles/elgg/defaults/main.yml
- include_vars: roles/mediawiki/defaults/main.yml
- include_vars: roles/nextcloud/defaults/main.yml
- include_vars: roles/wordpress/defaults/main.yml

- name: Provision MySql
  include_tasks: roles/mysql/tasks/prov-db.yml

#- name: Set passwords for MySql
#  include_tasks: roles/mysql-enable/tasks/passwd.yml

#- name: Provision Elgg
#  include_tasks: roles/elgg/tasks/setup.yml
#  when: elgg_install | bool

#- name: Provision MediaWiki
#  include_tasks: roles/mediawiki/tasks/setup.yml
#  when: mediawiki_install | bool

#- name: Provision NextCloud
#  include_tasks: roles/nextcloud/tasks/setup.yml
#  when: nextcloud_install | bool

#- name: Provision WordPress
#  include_tasks: roles/wordpress/tasks/setup.yml
#  when: wordpress_install | bool
