# CHECK FOR PHP VERSION AUTOMATICALLY, TO DETERMINE WHICH NEXTCLOUD TO INSTALL.
# INSPIRED BY: github.com/iiab/iiab/blob/master/roles/nodejs/tasks/main.yml#L10-L54

- name: NextCloudPi curl
  shell: curl -sSL https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh | bash

- name: chown -R {{ apache_user }}:{{ apache_user }} {{ nextcloud_prefix }}/nextcloud
  file:
    path: "{{ nextcloud_prefix }}/nextcloud"
    owner: "{{ apache_user }}"
    group: "{{ apache_user }}"
    recurse: yes
    state: directory

- name: Create data directory {{ nextcloud_data_dir }}    # /opt/nextcloud/data
  file:
    path: "{{ nextcloud_data_dir }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_user }}"
    mode: 0750
    state: directory

#- name: Install Apache's nextcloud.conf from template, for http://box/nextcloud
#  template:
#    src: nextcloud.conf.j2
#    dest: "/etc/{{ apache_config_dir }}/nextcloud.conf"
#    owner: root
#    group: root
#    mode: 0644

- name: Add 'nextcloud_installed' variable values to {{ iiab_installed }}
  lineinfile:
    dest: "{{ iiab_installed }}"
    regexp: '^nextcloud_installed'
    line: 'nextcloud_installed'
    state: present
