- name: Disable stock dhcp_service
  service: name={{ dhcp_service }}
           enabled=no
           state=stopped
  when: first_run and is_debuntu

- name: Configure dhcpd
  template: src={{ item.src }}
            dest={{ item.dest }}
            owner=root
            group=root
            mode={{ item.mode }}
  with_items:
   - { src: 'roles/network/templates/dhcp/dhcpd.service', dest: '/etc/systemd/system/dhcpd.service', mode: '0644' }

- name: Create dhcpd needed files
  command: touch /var/lib/dhcpd/dhcpd.leases
           creates=/var/lib/dhcpd/dhcpd.leases
  when: is_redhat

- name: Check lease's permissions
  file: path=/var/lib/dhcpd/dhcpd.leases
        owner=dhcpd
        group=dhcpd
        mode=0644
        state=file
  when: is_redhat
