- name: Create a config file for hostapd
  template: src=hostapd/hostapd.conf.j2
            dest=/etc/hostapd/hostapd.conf
            owner=root
            group=root
            mode=0644
  when: iiab_wireless_lan_iface is defined

- name: Create a config template for hostapd
  template: src=hostapd/iiab-hostapd.conf.j2
            dest=/etc/hostapd/hostapd.conf.template
            owner=root
            group=root
            mode=0644
  when: discovered_wireless_iface is defined

- name: Enable the Access Point 'hostapd' service
  service: enabled=yes
           name=hostapd.service
  when: iiab_wireless_lan_iface is defined and iiab_network_mode != "Appliance" and hostapd_enabled

- name: Use custom systemd unit file to start 'hostapd' service
  template: src=hostapd/hostapd.service.j2
            dest=/etc/systemd/system/hostapd.service
            owner=root
            group=root
            mode=0644

- name: Enable the Access Point 'hostapd' service
  service: enabled=yes
           name=hostapd.service
  when: iiab_wireless_lan_iface is defined and iiab_network_mode != "Appliance" and hostapd_enabled
