- include: detected_network.yml
  when: not installing
  tags:
    - network
    - network-discover

- include: computed_network.yml
  when: not installing
  tags:
    - network
    - network-discover

##### Start static ip address info for first run #####
#- include: static.yml
#  when: 'iiab_wan_iface != "none" and wan_ip != "dhcp"'
##### End static ip address info

- include: hosts.yml
  tags:
    - network
    - hostname
    - domain

##### end hostname setup
##### start install portion
# only needs to be done once
- include: installing.yml
  tags:
    - network
    - domain
    - named
    - dhcpd
    - dnsmasq
    - squid
    - domain
#  when: hostname_change.changed or installing

- include: avahi.yml
  tags:
    - network
    - domain

#### end install portion
#### start network layout
# setting installing would skip configuring network
# but would configure but not start services
- include: computed_network.yml
  when: not installing
  tags:
    - network
    - network-discover

- include: computed_services.yml
  tags:
    - network
    - named
    - dhcpd
    - dnsmasq
    - squid

# templates needed from above install section live here
- include: enable_services.yml
  tags:
    - network
    - named
    - dhcpd
    - dnsmasq
    - squid

- include: hostapd.yml
  tags:
    - network

- include: ifcfg_mods.yml
  when: not is_debuntu and not installing
  tags:
    - network

- include: debian.yml
  when: is_debuntu and not installing
  tags:
    - network

- name: Record iiab_wan_device
  lineinfile: dest=/etc/iiab/iiab.env
              regexp='^IIAB_WAN_DEVICE=*'
              line='IIAB_WAN_DEVICE="{{ iiab_wan_iface }}"'
              state=present
  when: not installing
  tags:
    - network

- name: Record iiab_lan_device
  lineinfile: dest=/etc/iiab/iiab.env
              regexp='^IIAB_LAN_DEVICE=*'
              line='IIAB_LAN_DEVICE="{{ iiab_lan_iface }}"'
              state=present
  when: not installing
  tags:
    - network
#### end network layout
#### start services

- include: restart.yml
  when: not installing
  tags:
    - network
    - named
    - dhcpd
    - dnsmasq
    - squid
#### end services
