- name: Enable http://box/moodle via NGINX, by installing {{ nginx_conf_dir }}/moodle-nginx.conf from template
  template:
    src: moodle-nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/moodle-nginx.conf"    # /etc/nginx/conf.d
  when: moodle_enabled | bool

- name: Disable http://box/moodle via NGINX, by removing {{ nginx_conf_dir }}/moodle-nginx.conf
  file:
    path: "{{ nginx_conf_dir }}/moodle-nginx.conf"    # /etc/nginx/conf.d
    state: absent
  when: not moodle_enabled

- name: Restart 'nginx' systemd service
  systemd:
    name: nginx
    state: restarted
  when: installing is defined
