# Local Add-ons

- name: ...IS BEGINNING ====================================
  set_fact:
        STAGE: 9
##### add your stuff here #####

# this script can be sourced to get IIAB location
- name: Recording STAGE 9 HAS COMPLETED ====================
  template:
        src: roles/1-prep/templates/iiab.env.j2
        dest: /etc/iiab/iiab.env
        owner: root
        group: root
        mode: 0644

- include_vars: roles/network/defaults/main.yml
- include_tasks: roles/network/tasks/detected_network.yml
  when: not installing
  tags:
    - network
    - network-discover

- include_tasks: roles/network/tasks/computed_network.yml
  when: not installing
  tags:
    - network
    - network-discover

##### Start static ip address info for first run #####
#- include_tasks: static.yml
#  when: 'iiab_wan_iface != "none" and wan_ip != "dhcp"'
##### End static ip address info

- include_tasks: roles/network/tasks/hosts.yml
  tags:
    - network
    - hostname
    - domain

- name: Configuring named on FQDN change
  include_tasks: roles/network/tasks/named.yml
  when: FQDN_changed and iiab_stage|int > 3

- name: Configuring dhcpd on FQDN change
  include_tasks: roles/network/tasks/dhcpd.yml
  when: FQDN_changed and iiab_stage|int > 3

#### start services
- include_tasks: roles/network/avahi.yml
  tags:
    - network

- include_tasks: roles/netwrork/tasks/hostapd.yml
  tags:
    - network
    - AP

- include_tasks: roles/network/computed_services.yml
  tags:
    - network
    - named
    - dhcpd
    - dnsmasq
    - squid

- include_tasks: roles/network/tasks/enable_services.yml
  tags:
    - network
    - named
    - dhcpd
    - dnsmasq
    - squid

#### end services
#### Start network layout

- include_tasks: roles/network/tasks/ifcfg_mods.yml
  tags:
    - network
  when: is_redhat and not installing

- include_tasks: roles/network/tasks/debian.yml
  tags:
    - network
  when: is_debuntu
#and not is_rpi  and not installing

#- include_tasks: rpi_debian.yml
#  tags:
#    - network
#  when: is_debuntu and is_rpi  and not installing

- name: Record iiab_wan_device
  lineinfile: dest=/etc/iiab/iiab.env
              regexp='^IIAB_WAN_DEVICE=*'
              line='IIAB_WAN_DEVICE="{{ iiab_wan_iface }}"'
              state=present
  when: not installing
  tags:
    - network

- name: Record iiab_lan_device
  lineinfile: dest=/etc/iiab/iiab.env
              regexp='^IIAB_LAN_DEVICE=*'
              line='IIAB_LAN_DEVICE="{{ iiab_lan_iface }}"'
              state=present
  when: not installing
  tags:
    - network

#### end network layout
- include_tasks: roles/network/tasks/restart.yml
  when: not installing
  tags:
    - network
    - named
    - dhcpd
    - dnsmasq
    - squid
