- name: Enable http://box/sugarizer & http://box/sugar via Apache
  command: a2ensite sugarizer.conf
  when: sugarizer_enabled

- name: Disable http://box/sugarizer & http://box/sugar via Apache
  command: a2dissite sugarizer.conf
  when: not sugarizer_enabled

- name: (Re)Start '{{ apache_service }}' systemd service
  systemd:
    name: "{{ apache_service }}"    # apache2 or httpd, as set in /opt/iiab/iiab/vars/<OS>.yml
    state: restarted
  when: installing is defined
