- name: Enable http://box/sugarizer via NGINX, by installing {{ nginx_conf_dir }}/sugarizer-nginx.conf from template
  template:
    src: sugarizer-nginx.conf
    dest: "{{ nginx_conf_dir }}/sugarizer-nginx.conf"    # /etc/nginx/conf.d
  when: sugarizer_enabled | bool

- name: Disable http://box/sugarizer via NGINX, by removing {{ nginx_conf_dir }}/sugarizer-nginx.conf
  file:
    path: "{{ nginx_conf_dir }}/sugarizer-nginx.conf"    # /etc/nginx/conf.d
    state: absent
  when: not sugarizer_enabled

- name: Restart 'nginx' systemd service
  systemd:
    name: nginx
    state: restarted
  when: installing is defined
