- name: Enable http://box/nodered via NGINX, by installing {{ nginx_conf_dir }}/nodered-nginx.conf from template
  template:
    src: nodered-nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nodered-nginx.conf"    # /etc/nginx/conf.d
  when: nodered_enabled | bool

- name: Disable http://box/nodered via NGINX, by removing {{ nginx_conf_dir }}/nodered-nginx.conf
  file:
    path: "{{ nginx_conf_dir }}/nodered-nginx.conf"    # /etc/nginx/conf.d
    state: absent
  when: not nodered_enabled

- name: Restart 'nginx' systemd service
  systemd:
    name: nginx
    state: restarted
  when: installing is defined
