- name: Enable http://box{{ kolibri_url }} via NGINX, by installing {{ nginx_conf_dir }}/kolibri-nginx.conf from template    # http://box/kolibri
  template:
    src: kolibri-nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/kolibri-nginx.conf"    # /etc/nginx/conf.d
  when: kolibri_enabled | bool

- name: Disable http://box{{ kolibri_url }} via NGINX, by removing {{ nginx_conf_dir }}/kolibri-nginx.conf    # http://box/kolibri
  file:
    path: "{{ nginx_conf_dir }}/kolibri-nginx.conf"    # /etc/nginx/conf.d
    state: absent
  when: not kolibri_enabled

- name: Restart 'nginx' systemd service
  systemd:
    name: nginx
    state: restarted
  when: installing is defined
