# Base Server

- name: ...IS BEGINNING =====================================
  command: echo

- name: HTTPD
  include_role:
    name: httpd
  # has no "when: XXXXX_install" flag
  tags: base, httpd

- name: IIAB-ADMIN
  include_role:
    name: iiab-admin
  # has no "when: XXXXX_install" flag
  tags: base, iiab-admin

- name: MYSQL
  include_role:
    name: mysql
  # has no "when: XXXXX_install" flag
  tags: base, mysql

- name: Restart httpd
  service: name={{ apache_service }}
           state=restarted
  when: not installing

- name: Recording STAGE 3 HAS COMPLETED =====================
  lineinfile: dest=/etc/iiab/iiab.env
              regexp='^STAGE=*'
              line='STAGE=3'
              state=present
