# Base Server

- name: ...IS BEGINNING =====================================
  set_fact:
      STAGE: 3

- name: Configuring wondershaper
  include_tasks: roles/network/tasks/wondershaper.yml
  when: wondershaper_install
  tags: wondershaper, network

- name: Configuring Squid
  include_tasks: roles/network/tasks/squid.yml
  when: squid_install
  tags: squid, network, domain

- name: Configuring named
  include_tasks: roles/network/tasks/named.yml
  when: FQDN_changed
  tags: named, network, domain

- name: Configuring dhcpd
  include_tasks: roles/network/tasks/dhcpd.yml
  when: FQDN_changed
  tags: dhcpd, network, domain

- name: HTTPD
  include_role:
    name: httpd
  # has no "when: XXXXX_install" flag
  tags: base, httpd

- name: IIAB-ADMIN
  include_role:
    name: iiab-admin
  # has no "when: XXXXX_install" flag
  tags: base, iiab-admin

- name: MYSQL
  include_role:
    name: mysql
  # has no "when: XXXXX_install" flag
  tags: base, mysql

- name: Make sure there is a content directory
  file: dest: "{{ doc_root }}/local_content"
        state: directory

- name: Restart httpd
  service: name: "{{ apache_service }}"
           state: restarted
  when: not installing

- name: Record STAGE 3 HAS COMPLETED ========================
  template:
        src: roles/1-prep/templates/iiab.stage.j2
        dest: /etc/iiab/iiab.env
        owner: root
        group: root
        mode: 0644
