- name: Make sure there is a content directory
  file: dest={{ doc_root }}/local_content
        state=directory

- name: Base Server Installed
  command: echo Base Server Installed

- name: Restart httpd
  service: name={{ apache_service }}
           state=restarted
  when: not installing

# If we got here we're done
#- name: Record base gui version
#  lineinfile: dest=/etc/iiab/iiab.env
#              regexp='^BASE_VERSION=*'
#              line='BASE_VERSION="{{ gui_version }}"'
#              state=present
