- name: Create symlink /usr/bin/iiab-diagnostics
  file:
    src: "{{ iiab_dir }}/scripts/iiab-diagnostics"
    dest: /usr/bin/iiab-diagnostics
    state: link

- name: Create {{ iiab_installed }}
  file:
    path: "{{ iiab_installed }}"
    state: touch

- name: Create {{ iiab_ini_file }}
  include_tasks: iiab_ini.yml
