- name: "Install ssh daemon using package: {{ sshd_package }}"
  when: sshd_installed is undefined

- name: Enable & Start ssh daemon ({{ sshd_service }}) if sshd_enabled
  systemd:
    name: "{{ sshd_service }}"
    daemon_reload: yes
    enabled: yes
    state: started
  when: sshd_enabled | bool

- name: Disable & Stop ssh daemon ({{ sshd_service }}) if not sshd_enabled
  systemd:
    name: "{{ sshd_service }}"
    enabled: no
    state: stopped
  when: not sshd_enabled

# iiab.ini?
